<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <PackageId>ConcurrentChunking.EntityFrameworkCore</PackageId>
        <Product>ConcurrentChunking.EntityFrameworkCore</Product>
        <Description>
            Allows parallel and pre-emptive loading of entities in a chunk-wise manner, resulting in much faster data access over time. This package provides LINQ extension methods for the ConcurrentChunking library.
        </Description>
        <IncludeSymbols>true</IncludeSymbols>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ConcurrentChunking\ConcurrentChunking.csproj"/>
    </ItemGroup>


    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
    </ItemGroup>

</Project>
